SELECT '=== NoteInventory ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NoteInventory' ORDER BY ORDINAL_POSITION;

SELECT '=== Products ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Products' ORDER BY ORDINAL_POSITION;

SELECT '=== ProductInventory ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductInventory' ORDER BY ORDINAL_POSITION;

SELECT '=== ProductCosts ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductCosts' ORDER BY ORDINAL_POSITION;

SELECT '=== MarketingCampaigns ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MarketingCampaigns' ORDER BY ORDINAL_POSITION;

SELECT '=== Coupons ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Coupons' ORDER BY ORDINAL_POSITION;

SELECT '=== ExpenseRecords ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExpenseRecords' ORDER BY ORDINAL_POSITION;

SELECT '=== GLTransactions ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GLTransactions' ORDER BY ORDINAL_POSITION;

SELECT '=== FundAccounts ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='FundAccounts' ORDER BY ORDINAL_POSITION;

SELECT '=== DailyStatistics ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DailyStatistics' ORDER BY ORDINAL_POSITION;

SELECT '=== ReconciliationLogs ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ReconciliationLogs' ORDER BY ORDINAL_POSITION;

SELECT '=== Orders ===' AS Info;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Orders' ORDER BY ORDINAL_POSITION;
