SELECT '=== ProductionOrders ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionOrders' ORDER BY ORDINAL_POSITION;

SELECT '=== AccordProductions ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AccordProductions' ORDER BY ORDINAL_POSITION;

SELECT '=== ProductManufacturing ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductManufacturing' ORDER BY ORDINAL_POSITION;

SELECT '=== PaymentRecords ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PaymentRecords' ORDER BY ORDINAL_POSITION;

SELECT '=== RawMaterials ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RawMaterials' ORDER BY ORDINAL_POSITION;

SELECT '=== RawMaterialInventory ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RawMaterialInventory' ORDER BY ORDINAL_POSITION;

SELECT '=== FragranceNotes ===' AS Info;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='FragranceNotes' ORDER BY ORDINAL_POSITION;
