SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PurchaseOrders' ORDER BY ORDINAL_POSITION;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PurchaseReceipts' ORDER BY ORDINAL_POSITION;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OrderDetailNoteSelections' ORDER BY ORDINAL_POSITION;
