UPDATE PurchaseOrders SET Status = N'Approved' WHERE PurchaseID = 14
INSERT INTO PurchaseReceipts (PurchaseID, SupplierID, ReceiptNo, ReceiptDate, Status, ReceivedBy, TotalReceivedQty, Notes, CreatedAt) VALUES (14, 1, N'REC-001', GETDATE(), N'Received', N'Ray88', 5500, N'Test', GETDATE())
INSERT INTO PurchaseReceiptDetails (ReceiptID, PurchaseDetailID, ReceivedQty, AcceptedQty, RejectedQty, UnitPrice) SELECT (SELECT MAX(ReceiptID) FROM PurchaseReceipts), DetailID, Quantity, Quantity, 0, UnitPrice FROM PurchaseOrderDetails WHERE PurchaseID = 14
UPDATE PurchaseOrders SET Status = N'Completed' WHERE PurchaseID = 14
IF NOT EXISTS (SELECT 1 FROM RawMaterialInventory WHERE ItemCode = 'BN-001') INSERT INTO RawMaterialInventory (ItemCode, ItemName, StockQty, UnitPrice, Unit, CategoryCode, UpdatedAt) VALUES ('BN-001', N'Lavender Essence', 1000, 2.5, 'ML', 'RAW', GETDATE()) ELSE UPDATE RawMaterialInventory SET StockQty = StockQty + 1000 WHERE ItemCode = 'BN-001'
IF NOT EXISTS (SELECT 1 FROM RawMaterialInventory WHERE ItemCode = 'BN-002') INSERT INTO RawMaterialInventory (ItemCode, ItemName, StockQty, UnitPrice, Unit, CategoryCode, UpdatedAt) VALUES ('BN-002', N'Rose Absolute', 1000, 3.5, 'ML', 'RAW', GETDATE()) ELSE UPDATE RawMaterialInventory SET StockQty = StockQty + 1000 WHERE ItemCode = 'BN-002'
IF NOT EXISTS (SELECT 1 FROM RawMaterialInventory WHERE ItemCode = 'BN-003') INSERT INTO RawMaterialInventory (ItemCode, ItemName, StockQty, UnitPrice, Unit, CategoryCode, UpdatedAt) VALUES ('BN-003', N'Sandalwood Oil', 1000, 8.0, 'ML', 'RAW', GETDATE()) ELSE UPDATE RawMaterialInventory SET StockQty = StockQty + 1000 WHERE ItemCode = 'BN-003'
IF NOT EXISTS (SELECT 1 FROM RawMaterialInventory WHERE ItemCode = 'BN-004') INSERT INTO RawMaterialInventory (ItemCode, ItemName, StockQty, UnitPrice, Unit, CategoryCode, UpdatedAt) VALUES ('BN-004', N'White Musk', 500, 6.0, 'ML', 'RAW', GETDATE()) ELSE UPDATE RawMaterialInventory SET StockQty = StockQty + 500 WHERE ItemCode = 'BN-004'
IF NOT EXISTS (SELECT 1 FROM RawMaterialInventory WHERE ItemCode = 'BN-005') INSERT INTO RawMaterialInventory (ItemCode, ItemName, StockQty, UnitPrice, Unit, CategoryCode, UpdatedAt) VALUES ('BN-005', N'Bergamot EO', 2000, 1.8, 'ML', 'RAW', GETDATE()) ELSE UPDATE RawMaterialInventory SET StockQty = StockQty + 2000 WHERE ItemCode = 'BN-005'
SELECT 'DONE' AS Result
